backend:
  name: git-gateway
  branch: staging
media_folder: static/images/blog/000
public_folder: "/images/blog/000"
collections:
- name: "blog"
  label: Blog
  folder: "content/blog"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields: # The fields for each document, usually in front matter
  - {label: "type", name: "type", widget: "hidden", default: "post"}
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Publish Date", name: "date", widget: "datetime"}
  - {label: "Featured Image", name: "image", widget: "image"}
  - {label: "Categories", name: "categories", widget: "list"}
  - {label: "Tags", name: "tags", widget: "list"}
  - {label: "Body", name: "body", widget: "markdown"}
